version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1464948824
layout:
  /container-top/:
    -
      -
        'topleft 10': {  }
      -
        'topmain 80':
          -
            - system-messages-9828
      -
        'topright 10': {  }
  /container-navigation/:
    -
      -
        'navigationleft 10': {  }
      -
        'navigationmain 80':
          -
            - 'logo-5992 15'
            - 'menu-7876 85'
      -
        'navigationright 10': {  }
  /container-header/:
    -
      -
        'headerleft 10': {  }
      -
        'headermain 80':
          -
            - 'position-position-5067 70'
            - 'position-position-9651 30'
      -
        'headerright 10': {  }
  /container-above/:
    -
      -
        'aboveleft 10': {  }
      -
        'abovemain 80':
          -
            - position-position-3264
      -
        'aboveright 10': {  }
  /container-main/:
    -
      -
        'sidebar 10':
          -
            - position-position-8538
      -
        'mainbar 80':
          -
            - position-position-8547
          -
            - system-content-1120
      -
        'aside 10':
          -
            - position-position-8807
  /container-showcase/:
    -
      -
        'showcaseleft 10': {  }
      -
        'showcasemain 80':
          -
            - 'position-position-9435 33.3'
            - 'position-position-8620 33.3'
            - 'position-position-3083 33.3'
      -
        'showcaseright 10': {  }
  /container-slideshow/:
    -
      -
        'slideshowleft 10': {  }
      -
        'slideshowmain 80':
          -
            - position-position-6661
      -
        'slideshowright 10': {  }
  /container-utility/:
    -
      -
        'utilityleft 10': {  }
      -
        'utilitymain 80':
          -
            - position-position-5239
      -
        'utilityright 10': {  }
  /container-feature/:
    -
      -
        'featureleft 10': {  }
      -
        'featuremain 80':
          -
            - position-position-7980
      -
        'featureright 10': {  }
  /container-expanded/:
    -
      -
        'expandedleft 10': {  }
      -
        'expandedmain 80':
          -
            - 'position-position-8124 50'
            - 'position-position-8346 50'
      -
        'expandedright 10': {  }
  /container-extension/:
    -
      -
        'extensionleft 10': {  }
      -
        'extensionmain 80':
          -
            - position-position-4800
      -
        'extensionright 10': {  }
  /container-bottom/:
    -
      -
        'bottomleft 10': {  }
      -
        'bottommain 80':
          -
            - position-position-3343
      -
        'bottomright 10': {  }
  /container-footer/:
    -
      -
        'footerleft 10': {  }
      -
        'footermain 80': {  }
      -
        'footerright 10': {  }
  /container-copyright/:
    -
      -
        'copyrightleft 10': {  }
      -
        'copyrightmain 80':
          -
            - 'position-position-2316 33.3'
            - 'position-position-5872 33.3'
            - 'position-position-5432 33.3'
          -
            - spacer-3620
          -
            - 'position-position-6325 17'
            - 'position-position-9467 17'
            - 'position-position-3508 17'
            - 'position-position-9427 17'
            - 'position-position-9799 32'
          -
            - spacer-4015
          -
            - copyright-5748
      -
        'copyrightright 10': {  }
  offcanvas:
    -
      - mobile-menu-7951
structure:
  topleft:
    type: section
    subtype: aside
    title: 'Top Left'
    attributes:
      class: ''
    block:
      class: g-side-column
      fixed: '1'
  topmain:
    type: section
    title: 'Top Main'
    attributes:
      class: ''
    block:
      class: g-middle-column
      fixed: '1'
  topright:
    type: section
    subtype: aside
    title: 'Top Right'
    attributes:
      class: ''
    block:
      class: g-side-column
      fixed: '1'
  container-top:
    attributes:
      boxed: '3'
      class: ''
      extra: {  }
  navigationleft:
    type: section
    title: 'Navigation Left'
    attributes:
      class: ''
    block:
      class: g-side-column
      fixed: '1'
  navigationmain:
    type: section
    title: 'Navigation Main'
    attributes:
      class: ''
    block:
      class: g-middle-column
      fixed: '1'
  navigationright:
    type: section
    title: 'Navigation Right'
    attributes:
      class: ''
    block:
      class: g-side-column
      fixed: '1'
  container-navigation:
    attributes:
      boxed: '3'
      class: ''
      extra: {  }
  headerleft:
    type: section
    subtype: aside
    title: 'Header Left'
    attributes:
      class: ''
    block:
      class: g-side-column
      fixed: '1'
  headermain:
    type: section
    subtype: header
    title: 'Header Main'
    attributes:
      class: ''
    block:
      class: g-middle-column
      fixed: '1'
  headerright:
    type: section
    subtype: aside
    title: 'Header Right'
    attributes:
      class: ''
    block:
      class: g-side-column
      fixed: '1'
  container-header:
    attributes:
      boxed: '3'
      class: ''
      extra: {  }
  aboveleft:
    type: section
    subtype: aside
    title: 'Above Left'
    attributes:
      class: ''
    block:
      class: g-side-column
      fixed: '1'
  abovemain:
    type: section
    title: 'Above Main'
    attributes:
      class: ''
    block:
      class: g-middle-column
      fixed: '1'
  aboveright:
    type: section
    subtype: aside
    title: 'Above Right'
    attributes:
      class: ''
    block:
      class: g-side-column
      fixed: '1'
  container-above:
    attributes:
      boxed: '3'
      class: g-main-offset
      extra: {  }
  sidebar:
    type: section
    subtype: aside
    block:
      class: g-side-column
      fixed: '1'
  mainbar:
    type: section
    subtype: main
    title: Main
    block:
      class: g-middle-column
      fixed: '1'
  aside:
    block:
      class: g-side-column
      fixed: '1'
  container-main:
    attributes:
      boxed: '3'
  showcaseleft:
    type: section
    subtype: aside
    title: 'Showcase Left'
    attributes:
      class: ''
    block:
      class: g-side-column
      fixed: '1'
  showcasemain:
    type: section
    title: 'Showcase Main'
    attributes:
      class: ''
    block:
      class: g-middle-column
      fixed: '1'
  showcaseright:
    type: section
    subtype: aside
    title: 'Showcase Right'
    attributes:
      class: ''
    block:
      class: g-side-column
      fixed: '1'
  container-showcase:
    attributes:
      boxed: '3'
      class: ''
      extra: {  }
  slideshowleft:
    type: section
    subtype: aside
    title: 'Slideshow Left'
    attributes:
      class: ''
    block:
      class: g-side-column
      fixed: '1'
  slideshowmain:
    type: section
    title: 'Slideshow Main'
    attributes:
      class: ''
    block:
      class: g-middle-column
      fixed: '1'
  slideshowright:
    type: section
    subtype: aside
    title: 'Slideshow Right'
    attributes:
      class: ''
    block:
      class: g-side-column
      fixed: '1'
  container-slideshow:
    attributes:
      boxed: '3'
      class: ''
      extra: {  }
  utilityleft:
    type: section
    subtype: aside
    title: 'Utility Left'
    attributes:
      class: ''
    block:
      class: g-side-column
      fixed: '1'
  utilitymain:
    type: section
    title: 'Utility Main'
    attributes:
      class: ''
    block:
      class: g-middle-column
      fixed: '1'
  utilityright:
    type: section
    subtype: aside
    title: 'Utility Right'
    attributes:
      class: ''
    block:
      class: g-side-column
      fixed: '1'
  container-utility:
    attributes:
      boxed: '3'
      class: ''
      extra: {  }
  featureleft:
    type: section
    subtype: aside
    title: 'Feature Left'
    attributes:
      class: ''
    block:
      class: g-side-column
      fixed: '1'
  featuremain:
    type: section
    title: 'Feature Main'
    attributes:
      class: ''
    block:
      class: g-middle-column
      fixed: '1'
  featureright:
    type: section
    subtype: aside
    title: 'Feature Right'
    attributes:
      class: ''
    block:
      class: g-side-column
      fixed: '1'
  container-feature:
    attributes:
      boxed: '3'
      class: ''
      extra: {  }
  expandedleft:
    type: section
    subtype: aside
    title: 'Expanded Left'
    attributes:
      class: ''
    block:
      class: g-side-column
      fixed: '1'
  expandedmain:
    type: section
    title: 'Expanded Main'
    attributes:
      class: ''
    block:
      class: g-middle-column
      fixed: '1'
  expandedright:
    type: section
    subtype: aside
    title: 'Expanded Right'
    attributes:
      class: ''
    block:
      class: g-side-column
      fixed: '1'
  container-expanded:
    attributes:
      boxed: '3'
      class: ''
      extra: {  }
  extensionleft:
    type: section
    subtype: aside
    title: 'Extension Left'
    attributes:
      class: ''
    block:
      class: g-side-column
      fixed: '1'
  extensionmain:
    type: section
    title: 'Extension Main'
    attributes:
      class: ''
    block:
      class: g-middle-column
      fixed: '1'
  extensionright:
    type: section
    subtype: aside
    title: 'Extension Right'
    attributes:
      class: ''
    block:
      class: g-side-column
      fixed: '1'
  container-extension:
    attributes:
      boxed: '3'
      class: ''
      extra: {  }
  bottomleft:
    type: section
    subtype: aside
    title: 'Bottom Left'
    attributes:
      class: ''
    block:
      class: g-side-column
      fixed: '1'
  bottommain:
    type: section
    title: 'Bottom Main'
    attributes:
      class: ''
    block:
      class: g-middle-column
      fixed: '1'
  bottomright:
    type: section
    subtype: aside
    title: 'Bottom Right'
    attributes:
      class: ''
    block:
      class: g-side-column
      fixed: '1'
  container-bottom:
    attributes:
      boxed: '3'
      class: ''
      extra: {  }
  footerleft:
    type: section
    subtype: aside
    title: 'Footer Left'
    attributes:
      class: ''
    block:
      class: g-side-column
      fixed: '1'
  footermain:
    type: section
    subtype: footer
    title: 'Footer Main'
    attributes:
      class: ''
    block:
      class: g-middle-column
      fixed: '1'
  footerright:
    type: section
    subtype: aside
    title: 'Footer Right'
    attributes:
      class: ''
    block:
      class: g-side-column
      fixed: '1'
  container-footer:
    attributes:
      boxed: '3'
      class: ''
      extra: {  }
  copyrightleft:
    type: section
    subtype: aside
    title: 'Copyright Left'
    attributes:
      class: ''
    block:
      class: g-side-column
      fixed: '1'
  copyrightmain:
    type: section
    title: 'Copyright Main'
    attributes:
      class: ''
    block:
      class: g-middle-column
      fixed: '1'
  copyrightright:
    type: section
    subtype: aside
    title: 'Copyright Right'
    attributes:
      class: ''
    block:
      class: g-side-column
      fixed: '1'
  container-copyright:
    attributes:
      boxed: '3'
      class: 'fp-copyright'
      extra: {  }
content:
  menu-7876:
    block:
      variations: align-right
  position-position-5067:
    title: 'Header A'
    attributes:
      key: header-a
  position-position-9651:
    title: 'Header B'
    attributes:
      key: header-b
    block:
      class: 'nomarginleft nomarginbottom'
      variations: nopaddingall
  position-position-3264:
    title: 'Above A'
    attributes:
      key: above-a
    block:
      variations: center
      class: nomarginbottom
  position-position-8538:
    title: 'Sidebar A'
    attributes:
      key: sidebar-a
  position-position-8547:
    title: 'MainBar A'
    attributes:
      key: mainbar-a
  position-position-8807:
    title: 'Aside A'
    attributes:
      key: aside-a
  position-position-9435:
    title: 'Showcase A'
    attributes:
      key: showcase-a
    block:
      variations: box5
  position-position-8620:
    title: 'Showcase B'
    attributes:
      key: showcase-b
  position-position-3083:
    title: 'Showcase C'
    attributes:
      key: showcase-c
  position-position-6661:
    title: 'Slideshow A'
    attributes:
      key: slideshow-a
  position-position-5239:
    title: 'Utility A'
    attributes:
      key: utility-a
  position-position-7980:
    title: 'Feature A'
    attributes:
      key: feature-a
  position-position-8124:
    title: 'Expanded A'
    attributes:
      key: expanded-a
  position-position-8346:
    title: 'Expanded B'
    attributes:
      key: expanded-b
  position-position-4800:
    title: 'Extension A'
    attributes:
      key: extension-a
  position-position-3343:
    title: 'Bottom A'
    attributes:
      key: bottom-a
  position-position-2316:
    title: 'Copyright A'
    attributes:
      key: copyright-a
    block:
      class: g-simpleweather-footer
  position-position-5872:
    title: 'Copyright B'
    attributes:
      key: copyright-b
    block:
      class: g-newsletter-footer
  position-position-5432:
    title: 'Copyright C'
    attributes:
      key: copyright-c
    block:
      class: g-social-footer
  spacer-3620:
    block:
      class: g-bordered-spacer
  position-position-6325:
    title: 'Copyright D'
    attributes:
      key: copyright-d
  position-position-9467:
    title: 'Copyright E'
    attributes:
      key: copyright-e
  position-position-3508:
    title: 'Copyright F'
    attributes:
      key: copyright-f
  position-position-9427:
    title: 'Copyright G'
    attributes:
      key: copyright-g
  position-position-9799:
    title: 'Copyright H'
    attributes:
      key: copyright-h
  spacer-4015:
    block:
      class: g-bordered-spacer
  position-position-1076:
    title: 'Copyright I'
    attributes:
      key: copyright-i
    block:
      variations: center
  copyright-5748:
    block:
      variations: center
