name: Base Styles
description: Base styles for the Sienna theme
type: core

form:
  fields:

    background:
      type: input.colorpicker
      label: Base Background
      default: "#ffffff"
    text-color:
      type: input.colorpicker
      label: Base Text Color
      default: "#666666"
    favicon:
       type: input.imagepicker
       label: Favicon
       filter: '.(jpe?g|gif|png|svg|ico)$'
    background-image:
      type: input.imagepicker
      label: Background Image
      default: "gantry-media://backgrounds/header/img-01.jpg"
